name: Build and publish docs

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Install mk
      run: curl -sf -L https://raw.githubusercontent.com/slasyz/mk/master/install.sh 2>/dev/null | bash

    - name: Build and publish
      run: |
        git config --global user.email "slasyz@gmail.com"
        git config --global user.name "Github Actions"
        git config --global url."https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/".insteadOf "git@github.com:"

        cd $GITHUB_WORKSPACE/docs
        yarn
        mk deploy
