name: Build and publish release

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  do:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.18.0'

      - name: Install mk
        run: |
          go build -o mk .
          chmod a+x mk
          sudo cp mk /usr/local/bin/mk
      - name: Build everything
        run: mk build all

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: ./bin/mk-*
